const projects = [
  {
    id: "software-dashboard-template",
    title: "[Software Project Title]",
    category: "Software",
    tags: ["JavaScript", "API", "Dashboard"],
    thumbnail: "",
    gallery: ["", ""],
    summary: "[Add 1-2 sentence summary for a software build here.]",
    description: "[Add the longer software project description here. Include the problem, architecture, integrations, and measurable outcome.]",
    repoUrl: "https://github.com/",
    cadUrl: "",
    codeSnippet: "fetch('./data/status.json')\n  .then((response) => response.json())\n  .then(renderStatusPanel);"
  },
  {
    id: "software-automation-template",
    title: "[Automation Script Title]",
    category: "Software",
    tags: ["Python", "CSV", "Reporting"],
    thumbnail: "",
    gallery: ["", ""],
    summary: "[Add 1-2 sentence summary for an automation or tooling project here.]",
    description: "[Add the longer project description here. Describe the repetitive workflow, inputs, outputs, and validation steps.]",
    repoUrl: "https://github.com/",
    cadUrl: "",
    codeSnippet: ""
  },
  {
    id: "iot-telemetry-node",
    title: "[IoT Telemetry Project]",
    category: "IoT",
    tags: ["ESP32", "MQTT", "Node-RED"],
    thumbnail: "",
    gallery: ["", ""],
    summary: "[Add 1-2 sentence summary for an IoT telemetry build here.]",
    description: "[Add the longer IoT project description here. Include sensors, firmware, communication protocol, dashboard, and enclosure notes.]",
    repoUrl: "https://github.com/",
    cadUrl: "",
    codeSnippet: "client.publish('machine/status', JSON.stringify({ state, voltage, temperature }));"
  },
  {
    id: "iot-control-module",
    title: "[IoT Control Module]",
    category: "IoT",
    tags: ["Sensors", "Relays", "Telemetry"],
    thumbnail: "",
    gallery: ["", ""],
    summary: "[Add 1-2 sentence summary for a connected control module here.]",
    description: "[Add the longer project description here. Describe the hardware selection, wiring, safety assumptions, and software behavior.]",
    repoUrl: "https://github.com/",
    cadUrl: "",
    codeSnippet: ""
  },
  {
    id: "panel-motor-control",
    title: "[Panel Building Project]",
    category: "Panel Building",
    tags: ["DIN Rail", "VFD", "Control Wiring"],
    thumbnail: "",
    gallery: ["", ""],
    summary: "[Add 1-2 sentence summary for a control panel build here.]",
    description: "[Add the longer panel project description here. Include layout, protection, wiring standards, labeling, tests, and final documentation.]",
    repoUrl: "",
    cadUrl: "",
    codeSnippet: ""
  },
  {
    id: "panel-test-rig",
    title: "[Panel Test Rig]",
    category: "Panel Building",
    tags: ["PLC", "Terminals", "Commissioning"],
    thumbnail: "",
    gallery: ["", ""],
    summary: "[Add 1-2 sentence summary for a panel test rig or electrical assembly here.]",
    description: "[Add the longer project description here. Describe the test procedure, wiring checks, enclosure work, and operating constraints.]",
    repoUrl: "",
    cadUrl: "",
    codeSnippet: ""
  },
  {
    id: "cad-enclosure-design",
    title: "[CAD Enclosure Design]",
    category: "CAD",
    tags: ["Fusion 360", "3D Print", "Assembly"],
    thumbnail: "",
    gallery: ["", ""],
    summary: "[Add 1-2 sentence summary for an enclosure or mechanical design here.]",
    description: "[Add the longer CAD project description here. Include design constraints, materials, tolerance decisions, and fabrication method.]",
    repoUrl: "",
    cadUrl: "assets/cad/",
    codeSnippet: ""
  },
  {
    id: "cad-panel-layout",
    title: "[CAD Panel Layout]",
    category: "CAD",
    tags: ["Drawings", "DXF", "Fabrication"],
    thumbnail: "",
    gallery: ["", ""],
    summary: "[Add 1-2 sentence summary for a CAD layout or drawing package here.]",
    description: "[Add the longer CAD project description here. Mention mounting, access, service clearances, and exported files.]",
    repoUrl: "",
    cadUrl: "assets/cad/",
    codeSnippet: ""
  }
];
